/**
 * Chakra UI Library Loader
 * Full Chakra UI component library
 */
import * as Chakra from '@chakra-ui/react';
import type { LoadedLibrary } from '../library-loader';

const library: LoadedLibrary = {
  id: 'chakraui',
  name: 'Chakra UI',
  framework: 'react',
  components: {
    // Layout
    Box: Chakra.Box,
    Flex: Chakra.Flex,
    Grid: Chakra.Grid,
    GridItem: Chakra.GridItem,
    SimpleGrid: Chakra.SimpleGrid,
    Stack: Chakra.Stack,
    HStack: Chakra.HStack,
    VStack: Chakra.VStack,
    Wrap: Chakra.Wrap,
    WrapItem: Chakra.WrapItem,
    Container: Chakra.Container,
    Center: Chakra.Center,
    Square: Chakra.Square,
    Circle: Chakra.Circle,
    AspectRatio: Chakra.AspectRatio,
    Spacer: Chakra.Spacer,
    
    // Typography
    Text: Chakra.Text,
    Heading: Chakra.Heading,
    Highlight: Chakra.Highlight,
    
    // Forms
    Button: Chakra.Button,
    ButtonGroup: Chakra.ButtonGroup,
    IconButton: Chakra.IconButton,
    Input: Chakra.Input,
    InputGroup: Chakra.InputGroup,
    InputLeftAddon: Chakra.InputLeftAddon,
    InputRightAddon: Chakra.InputRightAddon,
    InputLeftElement: Chakra.InputLeftElement,
    InputRightElement: Chakra.InputRightElement,
    NumberInput: Chakra.NumberInput,
    NumberInputField: Chakra.NumberInputField,
    NumberInputStepper: Chakra.NumberInputStepper,
    NumberIncrementStepper: Chakra.NumberIncrementStepper,
    NumberDecrementStepper: Chakra.NumberDecrementStepper,
    PinInput: Chakra.PinInput,
    PinInputField: Chakra.PinInputField,
    Textarea: Chakra.Textarea,
    Select: Chakra.Select,
    Checkbox: Chakra.Checkbox,
    CheckboxGroup: Chakra.CheckboxGroup,
    Radio: Chakra.Radio,
    RadioGroup: Chakra.RadioGroup,
    Switch: Chakra.Switch,
    Slider: Chakra.Slider,
    SliderTrack: Chakra.SliderTrack,
    SliderFilledTrack: Chakra.SliderFilledTrack,
    SliderThumb: Chakra.SliderThumb,
    SliderMark: Chakra.SliderMark,
    RangeSlider: Chakra.RangeSlider,
    RangeSliderTrack: Chakra.RangeSliderTrack,
    RangeSliderFilledTrack: Chakra.RangeSliderFilledTrack,
    RangeSliderThumb: Chakra.RangeSliderThumb,
    FormControl: Chakra.FormControl,
    FormLabel: Chakra.FormLabel,
    FormHelperText: Chakra.FormHelperText,
    FormErrorMessage: Chakra.FormErrorMessage,
    
    // Data Display
    Badge: Chakra.Badge,
    Tag: Chakra.Tag,
    TagLabel: Chakra.TagLabel,
    TagLeftIcon: Chakra.TagLeftIcon,
    TagRightIcon: Chakra.TagRightIcon,
    TagCloseButton: Chakra.TagCloseButton,
    Avatar: Chakra.Avatar,
    AvatarBadge: Chakra.AvatarBadge,
    AvatarGroup: Chakra.AvatarGroup,
    Icon: Chakra.Icon,
    Image: Chakra.Image,
    Code: Chakra.Code,
    Kbd: Chakra.Kbd,
    List: Chakra.List,
    ListItem: Chakra.ListItem,
    ListIcon: Chakra.ListIcon,
    OrderedList: Chakra.OrderedList,
    UnorderedList: Chakra.UnorderedList,
    Table: Chakra.Table,
    Thead: Chakra.Thead,
    Tbody: Chakra.Tbody,
    Tfoot: Chakra.Tfoot,
    Tr: Chakra.Tr,
    Th: Chakra.Th,
    Td: Chakra.Td,
    TableCaption: Chakra.TableCaption,
    TableContainer: Chakra.TableContainer,
    Stat: Chakra.Stat,
    StatLabel: Chakra.StatLabel,
    StatNumber: Chakra.StatNumber,
    StatHelpText: Chakra.StatHelpText,
    StatArrow: Chakra.StatArrow,
    StatGroup: Chakra.StatGroup,
    Card: Chakra.Card,
    CardHeader: Chakra.CardHeader,
    CardBody: Chakra.CardBody,
    CardFooter: Chakra.CardFooter,
    
    // Feedback
    Alert: Chakra.Alert,
    AlertIcon: Chakra.AlertIcon,
    AlertTitle: Chakra.AlertTitle,
    AlertDescription: Chakra.AlertDescription,
    Progress: Chakra.Progress,
    CircularProgress: Chakra.CircularProgress,
    CircularProgressLabel: Chakra.CircularProgressLabel,
    Skeleton: Chakra.Skeleton,
    SkeletonCircle: Chakra.SkeletonCircle,
    SkeletonText: Chakra.SkeletonText,
    Spinner: Chakra.Spinner,
    
    // Overlay
    Modal: Chakra.Modal,
    ModalOverlay: Chakra.ModalOverlay,
    ModalContent: Chakra.ModalContent,
    ModalHeader: Chakra.ModalHeader,
    ModalFooter: Chakra.ModalFooter,
    ModalBody: Chakra.ModalBody,
    ModalCloseButton: Chakra.ModalCloseButton,
    AlertDialog: Chakra.AlertDialog,
    AlertDialogOverlay: Chakra.AlertDialogOverlay,
    AlertDialogContent: Chakra.AlertDialogContent,
    AlertDialogHeader: Chakra.AlertDialogHeader,
    AlertDialogBody: Chakra.AlertDialogBody,
    AlertDialogFooter: Chakra.AlertDialogFooter,
    AlertDialogCloseButton: Chakra.AlertDialogCloseButton,
    Drawer: Chakra.Drawer,
    DrawerOverlay: Chakra.DrawerOverlay,
    DrawerContent: Chakra.DrawerContent,
    DrawerHeader: Chakra.DrawerHeader,
    DrawerBody: Chakra.DrawerBody,
    DrawerFooter: Chakra.DrawerFooter,
    DrawerCloseButton: Chakra.DrawerCloseButton,
    Popover: Chakra.Popover,
    PopoverTrigger: Chakra.PopoverTrigger,
    PopoverContent: Chakra.PopoverContent,
    PopoverHeader: Chakra.PopoverHeader,
    PopoverBody: Chakra.PopoverBody,
    PopoverFooter: Chakra.PopoverFooter,
    PopoverArrow: Chakra.PopoverArrow,
    PopoverCloseButton: Chakra.PopoverCloseButton,
    PopoverAnchor: Chakra.PopoverAnchor,
    Tooltip: Chakra.Tooltip,
    Menu: Chakra.Menu,
    MenuButton: Chakra.MenuButton,
    MenuList: Chakra.MenuList,
    MenuItem: Chakra.MenuItem,
    MenuItemOption: Chakra.MenuItemOption,
    MenuGroup: Chakra.MenuGroup,
    MenuOptionGroup: Chakra.MenuOptionGroup,
    MenuDivider: Chakra.MenuDivider,
    
    // Navigation
    Tabs: Chakra.Tabs,
    TabList: Chakra.TabList,
    Tab: Chakra.Tab,
    TabPanels: Chakra.TabPanels,
    TabPanel: Chakra.TabPanel,
    TabIndicator: Chakra.TabIndicator,
    Breadcrumb: Chakra.Breadcrumb,
    BreadcrumbItem: Chakra.BreadcrumbItem,
    BreadcrumbLink: Chakra.BreadcrumbLink,
    BreadcrumbSeparator: Chakra.BreadcrumbSeparator,
    Link: Chakra.Link,
    LinkOverlay: Chakra.LinkOverlay,
    LinkBox: Chakra.LinkBox,
    SkipNavLink: Chakra.SkipNavLink,
    SkipNavContent: Chakra.SkipNavContent,
    Stepper: Chakra.Stepper,
    Step: Chakra.Step,
    StepIndicator: Chakra.StepIndicator,
    StepStatus: Chakra.StepStatus,
    StepTitle: Chakra.StepTitle,
    StepDescription: Chakra.StepDescription,
    StepSeparator: Chakra.StepSeparator,
    StepIcon: Chakra.StepIcon,
    StepNumber: Chakra.StepNumber,
    
    // Disclosure
    Accordion: Chakra.Accordion,
    AccordionItem: Chakra.AccordionItem,
    AccordionButton: Chakra.AccordionButton,
    AccordionPanel: Chakra.AccordionPanel,
    AccordionIcon: Chakra.AccordionIcon,
    
    // Other
    Divider: Chakra.Divider,
    CloseButton: Chakra.CloseButton,
    Show: Chakra.Show,
    Hide: Chakra.Hide,
    Portal: Chakra.Portal,
    Fade: Chakra.Fade,
    ScaleFade: Chakra.ScaleFade,
    Slide: Chakra.Slide,
    SlideFade: Chakra.SlideFade,
    Collapse: Chakra.Collapse,
    VisuallyHidden: Chakra.VisuallyHidden,
    VisuallyHiddenInput: Chakra.VisuallyHiddenInput,
    
    // Provider
    ChakraProvider: Chakra.ChakraProvider,
  },
  Provider: Chakra.ChakraProvider,
  loaded: true,
};

export default library;
