/**
 * Naive UI Library Loader
 * Full Naive UI component library
 */
import * as NaiveUI from 'naive-ui';
import type { LoadedLibrary } from '../library-loader';

const library: LoadedLibrary = {
  id: 'naiveui',
  name: 'Naive UI',
  framework: 'vue',
  components: {
    // General
    NButton: NaiveUI.NButton,
    NButtonGroup: NaiveUI.NButtonGroup,
    NIcon: NaiveUI.NIcon,
    NIconWrapper: NaiveUI.NIconWrapper,
    NGradientText: NaiveUI.NGradientText,
    NText: NaiveUI.NText,
    NH1: NaiveUI.NH1,
    NH2: NaiveUI.NH2,
    NH3: NaiveUI.NH3,
    NH4: NaiveUI.NH4,
    NH5: NaiveUI.NH5,
    NH6: NaiveUI.NH6,
    NP: NaiveUI.NP,
    NA: NaiveUI.NA,
    NBlockquote: NaiveUI.NBlockquote,
    NHr: NaiveUI.NHr,
    NUl: NaiveUI.NUl,
    NOl: NaiveUI.NOl,
    NLi: NaiveUI.NLi,
    
    // Layout
    NLayout: NaiveUI.NLayout,
    NLayoutHeader: NaiveUI.NLayoutHeader,
    NLayoutContent: NaiveUI.NLayoutContent,
    NLayoutFooter: NaiveUI.NLayoutFooter,
    NLayoutSider: NaiveUI.NLayoutSider,
    NGrid: NaiveUI.NGrid,
    NGi: NaiveUI.NGi,
    NSpace: NaiveUI.NSpace,
    NDivider: NaiveUI.NDivider,
    
    // Navigation
    NAnchor: NaiveUI.NAnchor,
    NAnchorLink: NaiveUI.NAnchorLink,
    NBreadcrumb: NaiveUI.NBreadcrumb,
    NBreadcrumbItem: NaiveUI.NBreadcrumbItem,
    NDropdown: NaiveUI.NDropdown,
    NMenu: NaiveUI.NMenu,
    NPagination: NaiveUI.NPagination,
    NSteps: NaiveUI.NSteps,
    NStep: NaiveUI.NStep,
    NTabs: NaiveUI.NTabs,
    NTabPane: NaiveUI.NTabPane,
    NBackTop: NaiveUI.NBackTop,
    
    // Data Input
    NAutoComplete: NaiveUI.NAutoComplete,
    NCascader: NaiveUI.NCascader,
    NCheckbox: NaiveUI.NCheckbox,
    NCheckboxGroup: NaiveUI.NCheckboxGroup,
    NColorPicker: NaiveUI.NColorPicker,
    NDatePicker: NaiveUI.NDatePicker,
    NDynamicInput: NaiveUI.NDynamicInput,
    NDynamicTags: NaiveUI.NDynamicTags,
    NForm: NaiveUI.NForm,
    NFormItem: NaiveUI.NFormItem,
    NFormItemGi: NaiveUI.NFormItemGi,
    NFormItemRow: NaiveUI.NFormItemRow,
    NInput: NaiveUI.NInput,
    NInputGroup: NaiveUI.NInputGroup,
    NInputGroupLabel: NaiveUI.NInputGroupLabel,
    NInputNumber: NaiveUI.NInputNumber,
    NMention: NaiveUI.NMention,
    NRadio: NaiveUI.NRadio,
    NRadioGroup: NaiveUI.NRadioGroup,
    NRadioButton: NaiveUI.NRadioButton,
    NRate: NaiveUI.NRate,
    NSelect: NaiveUI.NSelect,
    NSlider: NaiveUI.NSlider,
    NSwitch: NaiveUI.NSwitch,
    NTimePicker: NaiveUI.NTimePicker,
    NTransfer: NaiveUI.NTransfer,
    NTreeSelect: NaiveUI.NTreeSelect,
    NUpload: NaiveUI.NUpload,
    NUploadDragger: NaiveUI.NUploadDragger,
    
    // Data Display
    NAvatar: NaiveUI.NAvatar,
    NAvatarGroup: NaiveUI.NAvatarGroup,
    NBadge: NaiveUI.NBadge,
    NCalendar: NaiveUI.NCalendar,
    NCard: NaiveUI.NCard,
    NCarousel: NaiveUI.NCarousel,
    NCollapse: NaiveUI.NCollapse,
    NCollapseItem: NaiveUI.NCollapseItem,
    NCollapseTransition: NaiveUI.NCollapseTransition,
    NCountdown: NaiveUI.NCountdown,
    NDataTable: NaiveUI.NDataTable,
    NDescriptions: NaiveUI.NDescriptions,
    NDescriptionsItem: NaiveUI.NDescriptionsItem,
    NEmpty: NaiveUI.NEmpty,
    NImage: NaiveUI.NImage,
    NImageGroup: NaiveUI.NImageGroup,
    NList: NaiveUI.NList,
    NListItem: NaiveUI.NListItem,
    NNumberAnimation: NaiveUI.NNumberAnimation,
    NStatistic: NaiveUI.NStatistic,
    NTable: NaiveUI.NTable,
    NTag: NaiveUI.NTag,
    NThing: NaiveUI.NThing,
    NTime: NaiveUI.NTime,
    NTimeline: NaiveUI.NTimeline,
    NTimelineItem: NaiveUI.NTimelineItem,
    NTree: NaiveUI.NTree,
    NLog: NaiveUI.NLog,
    NCode: NaiveUI.NCode,
    NEllipsis: NaiveUI.NEllipsis,
    NScrollbar: NaiveUI.NScrollbar,
    NVirtualList: NaiveUI.NVirtualList,
    NWatermark: NaiveUI.NWatermark,
    
    // Feedback
    NAlert: NaiveUI.NAlert,
    NDialog: NaiveUI.NDialog,
    NDrawer: NaiveUI.NDrawer,
    NDrawerContent: NaiveUI.NDrawerContent,
    // NMessage and NNotification are imperative APIs, not components
    NModal: NaiveUI.NModal,
    NPopconfirm: NaiveUI.NPopconfirm,
    NPopover: NaiveUI.NPopover,
    NPopselect: NaiveUI.NPopselect,
    NProgress: NaiveUI.NProgress,
    NResult: NaiveUI.NResult,
    NSkeleton: NaiveUI.NSkeleton,
    NSpin: NaiveUI.NSpin,
    NTooltip: NaiveUI.NTooltip,
    
    // Config
    NConfigProvider: NaiveUI.NConfigProvider,
    NDialogProvider: NaiveUI.NDialogProvider,
    NLoadingBarProvider: NaiveUI.NLoadingBarProvider,
    NMessageProvider: NaiveUI.NMessageProvider,
    NModalProvider: NaiveUI.NModalProvider,
    NNotificationProvider: NaiveUI.NNotificationProvider,
    
    // Utility
    NAffix: NaiveUI.NAffix,
    NElement: NaiveUI.NElement,
    NEquation: NaiveUI.NEquation,
    NFloatButton: NaiveUI.NFloatButton,
    NFloatButtonGroup: NaiveUI.NFloatButtonGroup,
    NPerformantEllipsis: NaiveUI.NPerformantEllipsis,
  },
  loaded: true,
};

export default library;
